### ISSUE TITLE
Request.finish called after connection was lost

### ISSUE THREAD

**Issue by thepyguy** [scrapinghub/scrapyrt#109]
I am working with someone who is making a POST request from PHP so I am suspecting that their connection is terminating before the results are completed. The traceback is below...how can I go about fixing this ?

Is there a setting in scrapy RT I can use or to me it sounds like the client side is closing the connection before receiving the results. Here is the traceback.

http://dpaste.com/06ES3A9

What exactly is happening here and how can I fix this or provide instructions to my friends working in PHP to fix this issue with Request.notifyFinish or other method ?

**Comment by nyov** [comment]
Since you are calling from PHP, I would hazard a guess that you need to increas PHP's `max_execution_time` to wait longer on the result before terminating? Or if that's not the culprit, perhaps [`stream_set_timeout`](https://www.php.net/manual/en/function.stream-set-timeout.php) is.

In any case, why don't you ask your friend to check the logs on the PHP side? That should give you a definitive answer.

**Comment by pawelmhm** [comment]
I've seen this in production too and it's not causing any concern, just traceback in logs. Still we could track it and handle it by logging nicer error instead of raw traceback, so some improvement might be nedeed here.

**Comment by thepyguy** [comment]
Sorry for the late reply, but @nyov had the solution. The php developer had made mistakes in accessing the API. Thank you for your help.
