### ISSUE TITLE
https seems not supported? 

### ISSUE THREAD

**Issue by dearvinitsr** [scrapinghub/scrapyrt#42]
Is there any support for https link crawling with scrapyrt?
With Scrapy command, data can be exported easily but Scrapyrt api not returning data for https link.

regards
Vinit

**Comment by pawelmhm** [comment]
https should work fine @dearvinitsr can you add some examples? Are you speaking about https links crawled by spider in ScrapyRT or about deploying ScrapyRT with https? Both should be possible, second thing (deploying scrapyrt via htttps so that you can access it via https://localhost/crawl.json) is not documented, but possible.

**Comment by chekunkov** [comment]
No response in 4 months, let's close this

**Comment by mani619cash** [comment]
I wanted to send request to ScrapyRT via AJAX in one of my website (let say https://website.com) which uses HTTPS 

But I could not use ScrapyRT because ScrapyRT (https://website.com:9080) does not load with HTTPS... The page keeps loading and loading.
