### ISSUE TITLE
ubuntu(14.04) server

### ISSUE THREAD

**Issue by idaima** [scrapinghub/scrapyrt#52]
How to run scrapyrt on ubuntu server？

**Comment by pawelmhm** [comment]
hey @idaima can you install docker and launch docker images on your server? If yes then there is docker image that is definitely easiest way to get started. Probably easiest way is to clone this repo and then docker build docker start. Perhaps we could release some official image so that you could do docker pull as we well I see there are some unofficial images https://hub.docker.com/r/localistico/scrapyrt/ but we do not supported them this is some other user releasing their docker image for scrapyrt.

**Comment by pawelmhm** [comment]
#53 will fix docker and create official docker image in dockerhub, next step we'll provide better info about deploys in docs

**Comment by pawelmhm** [comment]
fixed in https://github.com/scrapinghub/scrapyrt/pull/64
